### ISSUE TITLE
[mac] How to display it in the menu bar?

### ISSUE THREAD

**Issue by dotWee** [imwally/battstat#1]
Is there any chance to get it displaying in the menu bar? Would be awesome to provide an how-to instruction!

**Comment by kvelicka** [comment]
https://github.com/matryer/bitbar will do it for ya 👍

**Comment by imwally** [comment]
Yeah, I think what @kvelicka said would be the easiest method. Maybe I'll add a section to the README that mentions bitbar as an option.

**Comment by dotWee** [comment]
Thanks! I'll take a look at that.

**Comment by imwally** [comment]
@dotWee I've updated the README with instructions on how to use it with bitbar. Thanks again @kvelicka
