### ISSUE TITLE
Missing percentage on OS X El Capitan 10.11.6

### ISSUE THREAD

**Issue by jftuga** [imwally/battstat#2]
`battstat {i} {t} {p}`

**current battstatt outputs**...

` ⚡  calc...  charging`

--

` 🔋  calc...  discharging`

--

`pmset -g batt`

**2 different types of outputs when on battery**...

`Now drawing from 'Battery Power'`

 `-InternalBattery-0 	89%; discharging; 4:47 remaining present: true`

--

`Now drawing from 'Battery Power'`

 `-InternalBattery-0 	90%; discharging; (no estimate) present: true`

**3 different types of outputs while charging**...

`Now drawing from 'AC Power'`

 `-InternalBattery-0 	88%; AC attached; not charging present: true`

--

`Now drawing from 'AC Power'`

 `-InternalBattery-0 	90%; charging; (no estimate) present: true`

--

`Now drawing from 'AC Power'`

` -InternalBattery-0 	91%; charging; 0:25 remaining present: true`

**Comment by imwally** [comment]
@jftuga thanks for pointing this out. When you get a chance could you test out the latest version?

**Comment by jftuga** [comment]
I tested and it is working great now.  Thanks for fixing.
