### ISSUE TITLE
Specifying `--charging-icon` or `--discharging-icon` should not break the default usage

### ISSUE THREAD

**Issue by o-nikolas** [imwally/battstat#7]
If you call `battstat` with no options you get a nice default template (which seems equivalent to `{t} {p} {i}`:
```
onikolas@u5d27a7aaa47758:~$ battstat
 0:32  17%  🔋
```

But if you specify overrides for the icon (for e.g. the battstat is being displayed somewhere that does not support them) you get back an empty response instead of the default format with your icon overrides used (or even an error message).

What you get:
```
onikolas@u5d27a7aaa47758:~$ battstat  --discharging-icon "discharging"
 
```

What I think you should get:
```
onikolas@u5d27a7aaa47758:~$ battstat  --charging-icon "discharging"
 0:32  17%  discharging 
```

This is on Ubuntu 20.04

**Comment by imwally** [comment]
Hello!

Would you be able to give an example of where emojis are not supported? I would love to also see any error messages if possible too. 

Thank you!

**Comment by imwally** [comment]
Oh... I'm a dumb dumb. Now I get what you are saying. If you supply any arguments without supplying the replacement tokens then there is no output.

Great catch!

**Comment by o-nikolas** [comment]
> Oh... I'm a dumb dumb. Now I get what you are saying. If you supply any arguments without supplying the replacement tokens then there is no output.
> 
> Great catch!

Yupp! I've added a PR which fixes this I've been using it for months now and it's been great :)
